## SLAM parameters
Results:
  save_results: True
  save_dir: "results/tum"
  save_trj: True
  save_trj_kf_intv: 5
  use_gui: True
  eval_rendering: True
  use_wandb: False  

Dataset:
  type: 'droid'
  sensor_type: 'depth'
  save_only_kf: True
  use_droid_keyframe: True
  pcd_downsample: 60
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01
  refine_pose_from: 200000

Tracking:
  eval_ate: True
  eval_ate_every: 1
  eval_ate_after: 10
  eval_plot_flag: True
  eval_ate_all: True
  isotropic_loss_ratio: 0.6

Training:
  # Initialization
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_min_opacity: 0.005
  init_gaussian_extent: 30

  # Tracking
  use_droid_pose: True
  forward_pose: False
  prev_pose: False
  tracking_itr_num: 150
  tracking_itr_num_droid: 40
  gray_scale_threshold: 0.01

  # Mapping
  mapping_itr_num: 100
  gaussian_update_every: 300
  gaussian_update_offset: 30
  gaussian_th: 0.6
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20

  # Keyframe Selection
  window_size: 8
  pose_window: 4
  depth_ratio: 0.4
  kf_translation: 0.4
  kf_min_translation: 0.2
  kf_max_interval : 30
  kf_overlap: 0.8
  depth_error_percent: 0.3
  spherical_harmonics: True
  max_sh_degree: 3
  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001

## 3DGS default parameters
opt_params:
  iterations: 20000