inherit_from: "configs/rgbd/droid/base_config.yaml"

Dataset:
  dataset_path: "/media/jiaxin/Jiaxin-usb/data/data/kinect/house_droid"
  has_depth: True
  intrinsic:
    fx: 608.09136962890625
    fy: 608.2593994140625
    cx: 640.7423095703125
    cy: 363.48648071289062
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: False
    width: 1280
    height: 720
    depth_scale: 1000.0