inherit_from: "configs/rgbd/droid/base_config.yaml"
Dataset:
  dataset_path: "/media/jiaxin/Jiaxin/data/data/replica/room0_droid"
  single_thread: False
  intrinsic:
    fx: 600.0
    fy: 600.0
    cx: 599.5
    cy: 339.5
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1200
    height: 680
    depth_scale: 6553.5
    distorted: False