inherit_from: "configs/rgbd/droid/base_config.yaml"

Dataset:
  dataset_path: "/media/jiaxin/Jiaxin-usb/ma_final/data/tum/rgbd_dataset_freiburg2_desk/dataDroid"
  has_depth: True
  intrinsic:
    fx: 520.9
    fy: 521.0
    cx: 325.1
    cy: 249.7
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: False
    width: 640
    height: 480
    depth_scale: 5000.0