## SLAM parameters
Results:
  save_results: True
  save_dir: "results/kinect"
  save_trj: False
  save_trj_kf_intv: 5
  use_gui: True                                                                                                                                                                                                                                                    
  eval_rendering: True
  use_wandb: False  

Dataset:
  type: 'droid'
  sensor_type: 'depth'
  save_only_kf: True
  use_droid_keyframe: True
  pcd_downsample: 12800
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01
  global_optimization_during: True
  global_optimization_num: 4
  global_optimization_iter_max: 25000
  refine_pose_from: 2000

Tracking:
  eval_ate: False
  eval_ate_every: 100
  eval_ate_after: 100
  eval_plot_flag: True
  eval_ate_all: True
  isotropic_loss_ratio: 0.3

Training:
  # Initialization
  init_itr_num: 1050
  init_gaussian_update: 500
  init_gaussian_reset: 2000
  init_min_opacity: 0.005
  init_gaussian_extent: 30
  # Tracking and Mapping
  use_droid_pose: True
  forward_pose: False
  prev_pose: False
  tracking_itr_num: 150
  tracking_itr_num_droid: 5
  mapping_itr_num: 150
  gaussian_update_every: 1000
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20
  window_size: 8
  pose_window: 3
  edge_threshold: 1.1
  gray_scale_threshold: 0.01
  depth_ratio: 0.1
  kf_translation: 0.25
  kf_min_translation: 0.25
  kf_max_interval : 30
  kf_overlap: 0.5
  kf_cutoff: 0.3
  prune_mode: 'slam'
  single_thread: False
  spherical_harmonics: True
  max_sh_degree: 3
  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001

## 3DGS default parameters
opt_params:
  iterations: 20000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 20000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.02
  lambda_dssim: 0.2
  densification_interval: 400
  opacity_reset_interval: 2000
  densify_from_iter: 1000
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False